#!/usr/bin/env python3
"""
bundle_membrane.py — produce a self-contained, stdlib-only copy of the Leviathan
security membrane under ./membrane/, with a SHA-256 manifest.

The membrane's single source of truth is the Leviathan workspace. This script
COPIES the portable module set out of it so the Security Suite folder is a
complete, adoptable artifact — without a second, hand-maintained copy that could
drift. Re-run it whenever a membrane module changes:

    python bundle_membrane.py            # copy from the parent workspace
    python bundle_membrane.py --src DIR  # or from an explicit source dir

Then verify:  python membrane_selfcheck.py   (it finds ./membrane automatically)

Only stdlib-only modules are bundled. The OPTIONAL deep content layer
(deepfake_guard_expanded.py, which needs numpy+torch) is deliberately NOT copied:
the membrane falls back to the bundled light guards when it is absent.

The IMAGE NEUTRALISER tier — image_sanitizer.py (V13, perceptual-bound sub-perceptual
strip) and machine_code_detector.py (V14, QR / barcode / data-matrix redactor) — is
numpy-based BY NATURE (it transforms pixels), so it is NOT part of this stdlib bundle.
It has its own behaviour battery, image_membrane_selfcheck.py, run with numpy/PIL/scipy
present (cv2 optional, for the real-QR-decoder-defeated proof).
"""
import argparse
import hashlib
import json
import os
import shutil
import time

# The portable set, each with the one-line reason it belongs.
PORTABLE = {
    "leviathan_csam_floor.py":        "always-on CSAM floor (pure stdlib)",
    "deepfake_perceptual_guard.py":   "perceptual hidden-channel + intent + identity (stdlib; numpy optional)",
    "knowledge_guard.py":             "knowledge-bank / retrieval-injection guard (stdlib)",
    "text_sanitizer.py":              "invisible-Unicode strip + terminal-control/ANSI sanitizer (OWASP LLM01 #5 / LLM10 #8; pure stdlib)",
    "image_guard.py":                 "image decompression-bomb / malformed-image guard (stdlib; PIL optional)",
    "model_file_guard.py":            "model-file integrity decision engine (stdlib)",
    "leviathan_security.py":          "SecurityGate facade: check() / check_output() (stdlib; host settings optional)",
    "leviathan_blackhole.py":         "membrane orchestrator; falls back to the light guards with no heavy deps",
}


def _sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> int:
    ap = argparse.ArgumentParser(description="Bundle the portable security membrane.")
    here = os.path.dirname(os.path.abspath(__file__))
    ap.add_argument("--src", default=os.path.dirname(here),
                    help="source dir holding the membrane modules (default: parent)")
    ap.add_argument("--out", default=os.path.join(here, "membrane"),
                    help="output dir for the bundle (default: ./membrane)")
    args = ap.parse_args()

    os.makedirs(args.out, exist_ok=True)
    manifest = {"generated": time.strftime("%Y-%m-%d %H:%M:%S"),
                "source": os.path.abspath(args.src),
                "note": "Generated by bundle_membrane.py — do not edit by hand; "
                        "re-run to refresh. Optional deep layer "
                        "(deepfake_guard_expanded.py) intentionally excluded.",
                "files": {}}
    missing = []
    for name, reason in PORTABLE.items():
        src = os.path.join(args.src, name)
        if not os.path.isfile(src):
            missing.append(name)
            continue
        shutil.copy2(src, os.path.join(args.out, name))
        manifest["files"][name] = {"sha256": _sha256(src), "role": reason}
        print(f"  copied {name:34} {manifest['files'][name]['sha256'][:16]}…  ({reason})")

    if missing:
        print(f"\n  MISSING from source ({args.src}):")
        for m in missing:
            print(f"    - {m}")
        print("  Bundle incomplete. Point --src at the Leviathan workspace.")
        return 1

    with open(os.path.join(args.out, "manifest.json"), "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
    print(f"\n  wrote {len(manifest['files'])} modules + manifest.json to {args.out}")
    print("  verify with:  python membrane_selfcheck.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
